FROM django:onbuild
# RUN apt-get -y update && apt-get install -y 
RUN wget https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2 && \
    tar -xvf phantomjs-2.1.1-linux-x86_64.tar.bz2 && mv -v phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin

